[package]
name = "rust-websockets-time"
version = "0.1.0"
edition = "2024"

[dependencies]
futures-util = "0.3.31"
native-tls = "0.2.14"
tokio = { version = "1.48.0", features = ["full"] }
tokio-tungstenite = { version = "0.28.0", features = ["native-tls"] }
